"""Writes an analysis report to its .md file.

The reports under reports/ used to be assembled by hand: run a script, copy its stdout,
paste it into a markdown file between a prose header and a fence. That made every report a
manual step, and a manual step that is skipped is a report that quietly disagrees with the
code it claims to come from. The scripts write their own files now, and this is the one
place that knows the shape they take.

Deliberately free of heavy imports - no solvers, no pandas, no preformulation - so the
sweep report, which only reads CSVs, does not pay for the fleet machinery it never uses.
"""

from pathlib import Path

# src/analysis/ holds the scripts; reports/ holds only their output.
REPORTS = Path(__file__).resolve().parent / "reports"
FLEET_REPORTS = REPORTS / "fleet_reports"


def write_report(path: Path, title: str, summary: str, module: str, body: str) -> Path:
    """Assemble one report and write it: heading, prose, provenance, fenced body.

    `body` is the script's analysis text, fenced verbatim so its column alignment survives
    markdown. `module` names the command that regenerates the file, which is what makes a
    stale report identifiable as stale rather than merely wrong.

    Written with CRLF and `newline=""` to match the files already in the repo byte for byte;
    without that, a regeneration would rewrite every line of every report and bury real
    changes in whitespace noise.
    """
    text = f"# {title}\n\n{summary}\n\nGenerated by `python -m {module}`.\n\n```\n{body}\n```\n"

    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="\r\n", encoding="utf-8") as f:
        f.write(text)
    return path
